### ISSUE TITLE
Speed up dog listing page

### ISSUE THREAD

**Issue by jamesabolton** [TexasHuskyRescue/HuskyRescueCore#2]
The page listing the dogs from rescuegroups.org via a restful json API is very slow to load. https://texashuskyrescue.org/Adopt

Need to cache the data from this API and refresh once a day. Consider using a background process to check on a schedule to update the cached data.

Lazy load the images on each pop-up image slider

**Comment by danielbridges** [comment]
pull request added for this issue. https://github.com/TexasHuskyRescue/HuskyRescueCore/pull/27
Still need to address 'lazy load' for the images. Not sure how to do that. However, some changes to store the pictures separately in blob storage could be added and beneficial, but that's not addressed yet.
